---
- name: this playbook creates a file or directory
  hosts: all
    #become: true
  gather_facts: no
  tasks:
  - name: creating a file
    file:
      path: /home/ansadmin/demofile1
      state: touch

